import type { MigrationInterface, QueryRunner } from "typeorm";

export class IncludeGeneratedId1790603918153 implements MigrationInterface {
    name = 'IncludeGeneratedId1790603918153'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_sessions" ("session_id" varchar PRIMARY KEY NOT NULL, "workspace_id" varchar NOT NULL, "device_id" varchar NOT NULL, "started_at" text NOT NULL, "ended_at" text, "status" varchar CHECK( "status" IN ('ACTIVE','ENDED') ) NOT NULL, CONSTRAINT "FK_97207844c19e5c27d33a07f67c0" FOREIGN KEY ("device_id") REFERENCES "devices" ("device_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f56ab3c008dffd4a221c95c7cf3" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("workspace_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_sessions"("session_id", "workspace_id", "device_id", "started_at", "ended_at", "status") SELECT "session_id", "workspace_id", "device_id", "started_at", "ended_at", "status" FROM "sessions"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`ALTER TABLE "temporary_sessions" RENAME TO "sessions"`);
        await queryRunner.query(`CREATE TABLE "temporary_process_outputs" ("output_id" varchar PRIMARY KEY NOT NULL, "process_id" varchar NOT NULL, "stream_type" varchar CHECK( "stream_type" IN ('STDOUT','STDERR') ) NOT NULL, "main_content" text NOT NULL, "correlation_id" text NOT NULL, "created_at" text NOT NULL, CONSTRAINT "FK_fa47dfbcbfa7f0bd1e35bb3f742" FOREIGN KEY ("process_id") REFERENCES "processes" ("process_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_process_outputs"("output_id", "process_id", "stream_type", "main_content", "correlation_id", "created_at") SELECT "output_id", "process_id", "stream_type", "main_content", "correlation_id", "created_at" FROM "process_outputs"`);
        await queryRunner.query(`DROP TABLE "process_outputs"`);
        await queryRunner.query(`ALTER TABLE "temporary_process_outputs" RENAME TO "process_outputs"`);
        await queryRunner.query(`CREATE TABLE "temporary_processes" ("process_id" varchar PRIMARY KEY NOT NULL, "correlation_id" text NOT NULL, "request_id" varchar NOT NULL, "pid" integer NOT NULL, "command" text NOT NULL, "arguments" text NOT NULL, "current_state" varchar CHECK( "current_state" IN ('RUNNING','FAILED',' TERMINATED','COMPLETED') ) NOT NULL, "parent_pid" integer, "start_time" text NOT NULL, "end_time" text, "exit_code" integer, CONSTRAINT "UQ_ffe78e4dfafe8cda6cf4cf492ae" UNIQUE ("request_id"), CONSTRAINT "FK_ffe78e4dfafe8cda6cf4cf492ae" FOREIGN KEY ("request_id") REFERENCES "requests" ("request_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_processes"("process_id", "correlation_id", "request_id", "pid", "command", "arguments", "current_state", "parent_pid", "start_time", "end_time", "exit_code") SELECT "process_id", "correlation_id", "request_id", "pid", "command", "arguments", "current_state", "parent_pid", "start_time", "end_time", "exit_code" FROM "processes"`);
        await queryRunner.query(`DROP TABLE "processes"`);
        await queryRunner.query(`ALTER TABLE "temporary_processes" RENAME TO "processes"`);
        await queryRunner.query(`CREATE TABLE "temporary_action_proposals" ("action_id" varchar PRIMARY KEY NOT NULL, "ai_output_id" varchar NOT NULL, "correlation_id" text NOT NULL, "action_content" text NOT NULL, "status" varchar CHECK( "status" IN ('PENDING','APPROVED','REJECTED') ) NOT NULL, "created_at" text NOT NULL, "approved_at" text, CONSTRAINT "UQ_4e8c1aacdb0024fcce48b70f4a3" UNIQUE ("ai_output_id"), CONSTRAINT "FK_4e8c1aacdb0024fcce48b70f4a3" FOREIGN KEY ("ai_output_id") REFERENCES "ai_responses" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_action_proposals"("action_id", "ai_output_id", "correlation_id", "action_content", "status", "created_at", "approved_at") SELECT "action_id", "ai_output_id", "correlation_id", "action_content", "status", "created_at", "approved_at" FROM "action_proposals"`);
        await queryRunner.query(`DROP TABLE "action_proposals"`);
        await queryRunner.query(`ALTER TABLE "temporary_action_proposals" RENAME TO "action_proposals"`);
        await queryRunner.query(`CREATE TABLE "temporary_ai_responses" ("id" varchar PRIMARY KEY NOT NULL, "request_id" varchar NOT NULL, "request_type" varchar CHECK( "request_type" IN ('CHAT','ERROR_ANALYSIS','ACTION') ) NOT NULL, "provider" text NOT NULL, "model" text NOT NULL, "response_content" text NOT NULL, "duration" integer NOT NULL, "created_at" text NOT NULL, CONSTRAINT "UQ_026452136c98ad7df55bcbfc573" UNIQUE ("request_id"), CONSTRAINT "FK_026452136c98ad7df55bcbfc573" FOREIGN KEY ("request_id") REFERENCES "requests" ("request_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ai_responses"("id", "request_id", "request_type", "provider", "model", "response_content", "duration", "created_at") SELECT "id", "request_id", "request_type", "provider", "model", "response_content", "duration", "created_at" FROM "ai_responses"`);
        await queryRunner.query(`DROP TABLE "ai_responses"`);
        await queryRunner.query(`ALTER TABLE "temporary_ai_responses" RENAME TO "ai_responses"`);
        await queryRunner.query(`CREATE TABLE "temporary_devices" ("device_id" varchar PRIMARY KEY NOT NULL, "owner_id" varchar NOT NULL, "device_name" text NOT NULL, "device_label" text NOT NULL, "os_name" varchar CHECK( "os_name" IN ('ANDROID','WINDOWS','UBUNTU','DEBIAN','ARCH_LINUX','MACOS','LINUX','UNKNOWN') ) NOT NULL, "os_version" text NOT NULL, "os_build" text NOT NULL, "architecture" text NOT NULL, "device_model" text NOT NULL, "device_manufacturer" text NOT NULL, "hostname" text NOT NULL, "app_version" text NOT NULL, "installation_id" text NOT NULL, "synchronization_state" varchar CHECK( "synchronization_state" IN ('SYNCED','PENDING','SYNCHING','FAILED') ) NOT NULL, "updated_at" text NOT NULL, "last_seen" text NOT NULL, "created_at" text NOT NULL, CONSTRAINT "UQ_6a2bdb2b555cd6e1dea9442e3a4" UNIQUE ("installation_id"), CONSTRAINT "FK_cce90811a9e65e2c51357a0fbbd" FOREIGN KEY ("owner_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_devices"("device_id", "owner_id", "device_name", "device_label", "os_name", "os_version", "os_build", "architecture", "device_model", "device_manufacturer", "hostname", "app_version", "installation_id", "synchronization_state", "updated_at", "last_seen", "created_at") SELECT "device_id", "owner_id", "device_name", "device_label", "os_name", "os_version", "os_build", "architecture", "device_model", "device_manufacturer", "hostname", "app_version", "installation_id", "synchronization_state", "updated_at", "last_seen", "created_at" FROM "devices"`);
        await queryRunner.query(`DROP TABLE "devices"`);
        await queryRunner.query(`ALTER TABLE "temporary_devices" RENAME TO "devices"`);
        await queryRunner.query(`CREATE TABLE "temporary_user_secrets_credentials" ("credential_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "credential_type" varchar CHECK( "credential_type" IN ('ACCOUNT_PASSWORD','AI_API_KEY') ) NOT NULL, "provider" text NOT NULL, "credential_name" text NOT NULL, "credential_value" text NOT NULL, "status" varchar CHECK( "status" IN ('ACTIVE','EXPIRED','REVOKED') ) NOT NULL, "created_at" text NOT NULL, "updated_at" text NOT NULL, "expires_at" text, CONSTRAINT "FK_477f854eefea7f11154a0cd5911" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_user_secrets_credentials"("credential_id", "user_id", "credential_type", "provider", "credential_name", "credential_value", "status", "created_at", "updated_at", "expires_at") SELECT "credential_id", "user_id", "credential_type", "provider", "credential_name", "credential_value", "status", "created_at", "updated_at", "expires_at" FROM "user_secrets_credentials"`);
        await queryRunner.query(`DROP TABLE "user_secrets_credentials"`);
        await queryRunner.query(`ALTER TABLE "temporary_user_secrets_credentials" RENAME TO "user_secrets_credentials"`);
        await queryRunner.query(`CREATE TABLE "temporary_sessions" ("session_id" varchar PRIMARY KEY NOT NULL, "workspace_id" varchar NOT NULL, "device_id" varchar NOT NULL, "started_at" text NOT NULL, "ended_at" text, "status" varchar CHECK( "status" IN ('ACTIVE','ENDED') ) NOT NULL, CONSTRAINT "FK_97207844c19e5c27d33a07f67c0" FOREIGN KEY ("device_id") REFERENCES "devices" ("device_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f56ab3c008dffd4a221c95c7cf3" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("workspace_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_sessions"("session_id", "workspace_id", "device_id", "started_at", "ended_at", "status") SELECT "session_id", "workspace_id", "device_id", "started_at", "ended_at", "status" FROM "sessions"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`ALTER TABLE "temporary_sessions" RENAME TO "sessions"`);
        await queryRunner.query(`CREATE TABLE "temporary_process_outputs" ("output_id" varchar PRIMARY KEY NOT NULL, "process_id" varchar NOT NULL, "stream_type" varchar CHECK( "stream_type" IN ('STDOUT','STDERR') ) NOT NULL, "main_content" text NOT NULL, "correlation_id" text NOT NULL, "created_at" text NOT NULL, CONSTRAINT "FK_fa47dfbcbfa7f0bd1e35bb3f742" FOREIGN KEY ("process_id") REFERENCES "processes" ("process_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_process_outputs"("output_id", "process_id", "stream_type", "main_content", "correlation_id", "created_at") SELECT "output_id", "process_id", "stream_type", "main_content", "correlation_id", "created_at" FROM "process_outputs"`);
        await queryRunner.query(`DROP TABLE "process_outputs"`);
        await queryRunner.query(`ALTER TABLE "temporary_process_outputs" RENAME TO "process_outputs"`);
        await queryRunner.query(`CREATE TABLE "temporary_processes" ("process_id" varchar PRIMARY KEY NOT NULL, "correlation_id" text NOT NULL, "request_id" varchar NOT NULL, "pid" integer NOT NULL, "command" text NOT NULL, "arguments" text NOT NULL, "current_state" varchar CHECK( "current_state" IN ('RUNNING','FAILED',' TERMINATED','COMPLETED') ) NOT NULL, "parent_pid" integer, "start_time" text NOT NULL, "end_time" text, "exit_code" integer, CONSTRAINT "UQ_ffe78e4dfafe8cda6cf4cf492ae" UNIQUE ("request_id"), CONSTRAINT "FK_ffe78e4dfafe8cda6cf4cf492ae" FOREIGN KEY ("request_id") REFERENCES "requests" ("request_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_processes"("process_id", "correlation_id", "request_id", "pid", "command", "arguments", "current_state", "parent_pid", "start_time", "end_time", "exit_code") SELECT "process_id", "correlation_id", "request_id", "pid", "command", "arguments", "current_state", "parent_pid", "start_time", "end_time", "exit_code" FROM "processes"`);
        await queryRunner.query(`DROP TABLE "processes"`);
        await queryRunner.query(`ALTER TABLE "temporary_processes" RENAME TO "processes"`);
        await queryRunner.query(`CREATE TABLE "temporary_requests" ("request_id" varchar PRIMARY KEY NOT NULL, "correlation_id" text NOT NULL, "input_id" varchar NOT NULL, "classification_outcome" text NOT NULL, "context" text, "request_type" varchar CHECK( "request_type" IN ('AI','PROCESS') ) NOT NULL, "status" varchar CHECK( "status" IN ('PENDING','PROCESSING','COMPLETED','FAILED') ) NOT NULL, "created_at" text NOT NULL, "completed_at" text, CONSTRAINT "FK_513c536cc4773bb2e61b767b984" FOREIGN KEY ("input_id") REFERENCES "inputs" ("input_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_requests"("request_id", "correlation_id", "input_id", "classification_outcome", "context", "request_type", "status", "created_at", "completed_at") SELECT "request_id", "correlation_id", "input_id", "classification_outcome", "context", "request_type", "status", "created_at", "completed_at" FROM "requests"`);
        await queryRunner.query(`DROP TABLE "requests"`);
        await queryRunner.query(`ALTER TABLE "temporary_requests" RENAME TO "requests"`);
        await queryRunner.query(`CREATE TABLE "temporary_action_proposals" ("action_id" varchar PRIMARY KEY NOT NULL, "ai_output_id" varchar NOT NULL, "correlation_id" text NOT NULL, "action_content" text NOT NULL, "status" varchar CHECK( "status" IN ('PENDING','APPROVED','REJECTED') ) NOT NULL, "created_at" text NOT NULL, "approved_at" text, CONSTRAINT "UQ_4e8c1aacdb0024fcce48b70f4a3" UNIQUE ("ai_output_id"), CONSTRAINT "FK_4e8c1aacdb0024fcce48b70f4a3" FOREIGN KEY ("ai_output_id") REFERENCES "ai_responses" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_action_proposals"("action_id", "ai_output_id", "correlation_id", "action_content", "status", "created_at", "approved_at") SELECT "action_id", "ai_output_id", "correlation_id", "action_content", "status", "created_at", "approved_at" FROM "action_proposals"`);
        await queryRunner.query(`DROP TABLE "action_proposals"`);
        await queryRunner.query(`ALTER TABLE "temporary_action_proposals" RENAME TO "action_proposals"`);
        await queryRunner.query(`CREATE TABLE "temporary_ai_responses" ("id" varchar PRIMARY KEY NOT NULL, "request_id" varchar NOT NULL, "request_type" varchar CHECK( "request_type" IN ('CHAT','ERROR_ANALYSIS','ACTION') ) NOT NULL, "provider" text NOT NULL, "model" text NOT NULL, "response_content" text NOT NULL, "duration" integer NOT NULL, "created_at" text NOT NULL, CONSTRAINT "UQ_026452136c98ad7df55bcbfc573" UNIQUE ("request_id"), CONSTRAINT "FK_026452136c98ad7df55bcbfc573" FOREIGN KEY ("request_id") REFERENCES "requests" ("request_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ai_responses"("id", "request_id", "request_type", "provider", "model", "response_content", "duration", "created_at") SELECT "id", "request_id", "request_type", "provider", "model", "response_content", "duration", "created_at" FROM "ai_responses"`);
        await queryRunner.query(`DROP TABLE "ai_responses"`);
        await queryRunner.query(`ALTER TABLE "temporary_ai_responses" RENAME TO "ai_responses"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ai_responses" RENAME TO "temporary_ai_responses"`);
        await queryRunner.query(`CREATE TABLE "ai_responses" ("id" varchar PRIMARY KEY NOT NULL, "request_id" varchar NOT NULL, "request_type" varchar CHECK( "request_type" IN ('CHAT','ERROR_ANALYSIS','ACTION') ) NOT NULL, "provider" text NOT NULL, "model" text NOT NULL, "response_content" text NOT NULL, "duration" integer NOT NULL, "created_at" text NOT NULL, CONSTRAINT "UQ_026452136c98ad7df55bcbfc573" UNIQUE ("request_id"), CONSTRAINT "FK_026452136c98ad7df55bcbfc573" FOREIGN KEY ("request_id") REFERENCES "requests" ("request_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "ai_responses"("id", "request_id", "request_type", "provider", "model", "response_content", "duration", "created_at") SELECT "id", "request_id", "request_type", "provider", "model", "response_content", "duration", "created_at" FROM "temporary_ai_responses"`);
        await queryRunner.query(`DROP TABLE "temporary_ai_responses"`);
        await queryRunner.query(`ALTER TABLE "action_proposals" RENAME TO "temporary_action_proposals"`);
        await queryRunner.query(`CREATE TABLE "action_proposals" ("action_id" varchar PRIMARY KEY NOT NULL, "ai_output_id" varchar NOT NULL, "correlation_id" text NOT NULL, "action_content" text NOT NULL, "status" varchar CHECK( "status" IN ('PENDING','APPROVED','REJECTED') ) NOT NULL, "created_at" text NOT NULL, "approved_at" text, CONSTRAINT "UQ_4e8c1aacdb0024fcce48b70f4a3" UNIQUE ("ai_output_id"), CONSTRAINT "FK_4e8c1aacdb0024fcce48b70f4a3" FOREIGN KEY ("ai_output_id") REFERENCES "ai_responses" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "action_proposals"("action_id", "ai_output_id", "correlation_id", "action_content", "status", "created_at", "approved_at") SELECT "action_id", "ai_output_id", "correlation_id", "action_content", "status", "created_at", "approved_at" FROM "temporary_action_proposals"`);
        await queryRunner.query(`DROP TABLE "temporary_action_proposals"`);
        await queryRunner.query(`ALTER TABLE "requests" RENAME TO "temporary_requests"`);
        await queryRunner.query(`CREATE TABLE "requests" ("request_id" varchar PRIMARY KEY NOT NULL, "correlation_id" text NOT NULL, "input_id" varchar NOT NULL, "classification_outcome" text NOT NULL, "context" text, "request_type" varchar CHECK( "request_type" IN ('AI','PROCESS') ) NOT NULL, "status" varchar CHECK( "status" IN ('PENDING','PROCESSING','COMPLETED','FAILED') ) NOT NULL, "created_at" text NOT NULL, "completed_at" text, CONSTRAINT "FK_513c536cc4773bb2e61b767b984" FOREIGN KEY ("input_id") REFERENCES "inputs" ("input_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "requests"("request_id", "correlation_id", "input_id", "classification_outcome", "context", "request_type", "status", "created_at", "completed_at") SELECT "request_id", "correlation_id", "input_id", "classification_outcome", "context", "request_type", "status", "created_at", "completed_at" FROM "temporary_requests"`);
        await queryRunner.query(`DROP TABLE "temporary_requests"`);
        await queryRunner.query(`ALTER TABLE "processes" RENAME TO "temporary_processes"`);
        await queryRunner.query(`CREATE TABLE "processes" ("process_id" varchar PRIMARY KEY NOT NULL, "correlation_id" text NOT NULL, "request_id" varchar NOT NULL, "pid" integer NOT NULL, "command" text NOT NULL, "arguments" text NOT NULL, "current_state" varchar CHECK( "current_state" IN ('RUNNING','FAILED',' TERMINATED','COMPLETED') ) NOT NULL, "parent_pid" integer, "start_time" text NOT NULL, "end_time" text, "exit_code" integer, CONSTRAINT "UQ_ffe78e4dfafe8cda6cf4cf492ae" UNIQUE ("request_id"), CONSTRAINT "FK_ffe78e4dfafe8cda6cf4cf492ae" FOREIGN KEY ("request_id") REFERENCES "requests" ("request_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "processes"("process_id", "correlation_id", "request_id", "pid", "command", "arguments", "current_state", "parent_pid", "start_time", "end_time", "exit_code") SELECT "process_id", "correlation_id", "request_id", "pid", "command", "arguments", "current_state", "parent_pid", "start_time", "end_time", "exit_code" FROM "temporary_processes"`);
        await queryRunner.query(`DROP TABLE "temporary_processes"`);
        await queryRunner.query(`ALTER TABLE "process_outputs" RENAME TO "temporary_process_outputs"`);
        await queryRunner.query(`CREATE TABLE "process_outputs" ("output_id" varchar PRIMARY KEY NOT NULL, "process_id" varchar NOT NULL, "stream_type" varchar CHECK( "stream_type" IN ('STDOUT','STDERR') ) NOT NULL, "main_content" text NOT NULL, "correlation_id" text NOT NULL, "created_at" text NOT NULL, CONSTRAINT "FK_fa47dfbcbfa7f0bd1e35bb3f742" FOREIGN KEY ("process_id") REFERENCES "processes" ("process_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "process_outputs"("output_id", "process_id", "stream_type", "main_content", "correlation_id", "created_at") SELECT "output_id", "process_id", "stream_type", "main_content", "correlation_id", "created_at" FROM "temporary_process_outputs"`);
        await queryRunner.query(`DROP TABLE "temporary_process_outputs"`);
        await queryRunner.query(`ALTER TABLE "sessions" RENAME TO "temporary_sessions"`);
        await queryRunner.query(`CREATE TABLE "sessions" ("session_id" varchar PRIMARY KEY NOT NULL, "workspace_id" varchar NOT NULL, "device_id" varchar NOT NULL, "started_at" text NOT NULL, "ended_at" text, "status" varchar CHECK( "status" IN ('ACTIVE','ENDED') ) NOT NULL, CONSTRAINT "FK_97207844c19e5c27d33a07f67c0" FOREIGN KEY ("device_id") REFERENCES "devices" ("device_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f56ab3c008dffd4a221c95c7cf3" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("workspace_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "sessions"("session_id", "workspace_id", "device_id", "started_at", "ended_at", "status") SELECT "session_id", "workspace_id", "device_id", "started_at", "ended_at", "status" FROM "temporary_sessions"`);
        await queryRunner.query(`DROP TABLE "temporary_sessions"`);
        await queryRunner.query(`ALTER TABLE "user_secrets_credentials" RENAME TO "temporary_user_secrets_credentials"`);
        await queryRunner.query(`CREATE TABLE "user_secrets_credentials" ("credential_id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "credential_type" varchar CHECK( "credential_type" IN ('ACCOUNT_PASSWORD','AI_API_KEY') ) NOT NULL, "provider" text NOT NULL, "credential_name" text NOT NULL, "credential_value" text NOT NULL, "status" varchar CHECK( "status" IN ('ACTIVE','EXPIRED','REVOKED') ) NOT NULL, "created_at" text NOT NULL, "updated_at" text NOT NULL, "expires_at" text, CONSTRAINT "FK_477f854eefea7f11154a0cd5911" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "user_secrets_credentials"("credential_id", "user_id", "credential_type", "provider", "credential_name", "credential_value", "status", "created_at", "updated_at", "expires_at") SELECT "credential_id", "user_id", "credential_type", "provider", "credential_name", "credential_value", "status", "created_at", "updated_at", "expires_at" FROM "temporary_user_secrets_credentials"`);
        await queryRunner.query(`DROP TABLE "temporary_user_secrets_credentials"`);
        await queryRunner.query(`ALTER TABLE "devices" RENAME TO "temporary_devices"`);
        await queryRunner.query(`CREATE TABLE "devices" ("device_id" varchar PRIMARY KEY NOT NULL, "owner_id" varchar NOT NULL, "device_name" text NOT NULL, "device_label" text NOT NULL, "os_name" varchar CHECK( "os_name" IN ('ANDROID','WINDOWS','UBUNTU','DEBIAN','ARCH_LINUX','MACOS') ) NOT NULL, "os_version" text NOT NULL, "os_build" text NOT NULL, "architecture" text NOT NULL, "device_model" text NOT NULL, "device_manufacturer" text NOT NULL, "hostname" text NOT NULL, "app_version" text NOT NULL, "installation_id" text NOT NULL, "synchronization_state" varchar CHECK( "synchronization_state" IN ('SYNCED','PENDING','SYNCHING','FAILED') ) NOT NULL, "updated_at" text NOT NULL, "last_seen" text NOT NULL, "created_at" text NOT NULL, CONSTRAINT "UQ_6a2bdb2b555cd6e1dea9442e3a4" UNIQUE ("installation_id"), CONSTRAINT "FK_cce90811a9e65e2c51357a0fbbd" FOREIGN KEY ("owner_id") REFERENCES "users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "devices"("device_id", "owner_id", "device_name", "device_label", "os_name", "os_version", "os_build", "architecture", "device_model", "device_manufacturer", "hostname", "app_version", "installation_id", "synchronization_state", "updated_at", "last_seen", "created_at") SELECT "device_id", "owner_id", "device_name", "device_label", "os_name", "os_version", "os_build", "architecture", "device_model", "device_manufacturer", "hostname", "app_version", "installation_id", "synchronization_state", "updated_at", "last_seen", "created_at" FROM "temporary_devices"`);
        await queryRunner.query(`DROP TABLE "temporary_devices"`);
        await queryRunner.query(`ALTER TABLE "ai_responses" RENAME TO "temporary_ai_responses"`);
        await queryRunner.query(`CREATE TABLE "ai_responses" ("id" varchar PRIMARY KEY NOT NULL, "request_id" varchar NOT NULL, "request_type" varchar CHECK( "request_type" IN ('CHAT','ERROR_ANALYSIS','ACTION') ) NOT NULL, "provider" text NOT NULL, "model" text NOT NULL, "response_content" text NOT NULL, "duration" integer NOT NULL, "created_at" text NOT NULL, CONSTRAINT "UQ_026452136c98ad7df55bcbfc573" UNIQUE ("request_id"), CONSTRAINT "FK_026452136c98ad7df55bcbfc573" FOREIGN KEY ("request_id") REFERENCES "requests" ("request_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "ai_responses"("id", "request_id", "request_type", "provider", "model", "response_content", "duration", "created_at") SELECT "id", "request_id", "request_type", "provider", "model", "response_content", "duration", "created_at" FROM "temporary_ai_responses"`);
        await queryRunner.query(`DROP TABLE "temporary_ai_responses"`);
        await queryRunner.query(`ALTER TABLE "action_proposals" RENAME TO "temporary_action_proposals"`);
        await queryRunner.query(`CREATE TABLE "action_proposals" ("action_id" varchar PRIMARY KEY NOT NULL, "ai_output_id" varchar NOT NULL, "correlation_id" text NOT NULL, "action_content" text NOT NULL, "status" varchar CHECK( "status" IN ('PENDING','APPROVED','REJECTED') ) NOT NULL, "created_at" text NOT NULL, "approved_at" text, CONSTRAINT "UQ_4e8c1aacdb0024fcce48b70f4a3" UNIQUE ("ai_output_id"), CONSTRAINT "FK_4e8c1aacdb0024fcce48b70f4a3" FOREIGN KEY ("ai_output_id") REFERENCES "ai_responses" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "action_proposals"("action_id", "ai_output_id", "correlation_id", "action_content", "status", "created_at", "approved_at") SELECT "action_id", "ai_output_id", "correlation_id", "action_content", "status", "created_at", "approved_at" FROM "temporary_action_proposals"`);
        await queryRunner.query(`DROP TABLE "temporary_action_proposals"`);
        await queryRunner.query(`ALTER TABLE "processes" RENAME TO "temporary_processes"`);
        await queryRunner.query(`CREATE TABLE "processes" ("process_id" varchar PRIMARY KEY NOT NULL, "correlation_id" text NOT NULL, "request_id" varchar NOT NULL, "pid" integer NOT NULL, "command" text NOT NULL, "arguments" text NOT NULL, "current_state" varchar CHECK( "current_state" IN ('RUNNING','FAILED',' TERMINATED','COMPLETED') ) NOT NULL, "parent_pid" integer, "start_time" text NOT NULL, "end_time" text, "exit_code" integer, CONSTRAINT "UQ_ffe78e4dfafe8cda6cf4cf492ae" UNIQUE ("request_id"), CONSTRAINT "FK_ffe78e4dfafe8cda6cf4cf492ae" FOREIGN KEY ("request_id") REFERENCES "requests" ("request_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "processes"("process_id", "correlation_id", "request_id", "pid", "command", "arguments", "current_state", "parent_pid", "start_time", "end_time", "exit_code") SELECT "process_id", "correlation_id", "request_id", "pid", "command", "arguments", "current_state", "parent_pid", "start_time", "end_time", "exit_code" FROM "temporary_processes"`);
        await queryRunner.query(`DROP TABLE "temporary_processes"`);
        await queryRunner.query(`ALTER TABLE "process_outputs" RENAME TO "temporary_process_outputs"`);
        await queryRunner.query(`CREATE TABLE "process_outputs" ("output_id" varchar PRIMARY KEY NOT NULL, "process_id" varchar NOT NULL, "stream_type" varchar CHECK( "stream_type" IN ('STDOUT','STDERR') ) NOT NULL, "main_content" text NOT NULL, "correlation_id" text NOT NULL, "created_at" text NOT NULL, CONSTRAINT "FK_fa47dfbcbfa7f0bd1e35bb3f742" FOREIGN KEY ("process_id") REFERENCES "processes" ("process_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "process_outputs"("output_id", "process_id", "stream_type", "main_content", "correlation_id", "created_at") SELECT "output_id", "process_id", "stream_type", "main_content", "correlation_id", "created_at" FROM "temporary_process_outputs"`);
        await queryRunner.query(`DROP TABLE "temporary_process_outputs"`);
        await queryRunner.query(`ALTER TABLE "sessions" RENAME TO "temporary_sessions"`);
        await queryRunner.query(`CREATE TABLE "sessions" ("session_id" varchar PRIMARY KEY NOT NULL, "workspace_id" varchar NOT NULL, "device_id" varchar NOT NULL, "started_at" text NOT NULL, "ended_at" text, "status" varchar CHECK( "status" IN ('ACTIVE','ENDED') ) NOT NULL, CONSTRAINT "FK_97207844c19e5c27d33a07f67c0" FOREIGN KEY ("device_id") REFERENCES "devices" ("device_id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f56ab3c008dffd4a221c95c7cf3" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("workspace_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "sessions"("session_id", "workspace_id", "device_id", "started_at", "ended_at", "status") SELECT "session_id", "workspace_id", "device_id", "started_at", "ended_at", "status" FROM "temporary_sessions"`);
        await queryRunner.query(`DROP TABLE "temporary_sessions"`);
    }

}
